version: '2'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      XWIKI_VERSION: 7.4.3
      MYSQL_DRIVER_VERSION: 5.1.38
  db:
    image: "mysql:5"
    environment:
      MYSQL_ROOT_PASSWORD: xwiki
      MYSQL_USER: xwiki
      MYSQL_PASSWORD: xwiki
      MYSQL_DATABASE: xwiki

